apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp
    tier: front-end 
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

