kind: Service 
apiVersion: v1 
metadata:
  name: myapp-service 
spec:
  type: NodePort
  selector:
    app: myapp
    tier: front-end 
  ports:
    - nodePort: 30163
      port: 8080 
      targetPort: 80